# Name: Integration-environment.yml
# Description: This will build the integration environment

name: Setup Integration Environment

on:
  push:
    branches:
    - main
    - BuildContainersTest
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: docker compose -f "docker-compose.yml" up -d --build
      
    - name: Run the python unit tests for sentimental_analysis
      run: docker exec -it sentiment-analysis-api-1 sh -c 'pytest'

    - name: Run the frontend unit tests
      run: docker exec -it sentiment-analysis-api-1 sh -c 'cd app/web/tests && pytest'
      
    - name: Destroy the containers
      run: docker compose -f "docker-compose.yml" down
